# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'admin_panel.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AdminPanelWindow(object):
    def setupUi(self, AdminPanelWindow):
        AdminPanelWindow.setObjectName("AdminPanelWindow")
        AdminPanelWindow.resize(900, 600)
        self.centralwidget = QtWidgets.QWidget(AdminPanelWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_ver_aviones = QtWidgets.QPushButton(self.centralwidget)
        self.btn_ver_aviones.setGeometry(QtCore.QRect(20, 20, 100, 30))
        self.btn_ver_aviones.setObjectName("btn_ver_aviones")
        self.btn_agregar_avion = QtWidgets.QPushButton(self.centralwidget)
        self.btn_agregar_avion.setGeometry(QtCore.QRect(130, 20, 100, 30))
        self.btn_agregar_avion.setObjectName("btn_agregar_avion")
        self.btn_modificar_avion = QtWidgets.QPushButton(self.centralwidget)
        self.btn_modificar_avion.setGeometry(QtCore.QRect(240, 20, 100, 30))
        self.btn_modificar_avion.setObjectName("btn_modificar_avion")
        self.btn_eliminar_avion = QtWidgets.QPushButton(self.centralwidget)
        self.btn_eliminar_avion.setGeometry(QtCore.QRect(350, 20, 100, 30))
        self.btn_eliminar_avion.setObjectName("btn_eliminar_avion")
        self.tabla_aviones = QtWidgets.QTableWidget(self.centralwidget)
        self.tabla_aviones.setGeometry(QtCore.QRect(20, 70, 850, 300))
        self.tabla_aviones.setColumnCount(7)
        self.tabla_aviones.setRowCount(0)
        self.tabla_aviones.setObjectName("tabla_aviones")
        self.input_matricula = QtWidgets.QLineEdit(self.centralwidget)
        self.input_matricula.setGeometry(QtCore.QRect(20, 400, 200, 30))
        self.input_matricula.setObjectName("input_matricula")
        self.input_nombre = QtWidgets.QLineEdit(self.centralwidget)
        self.input_nombre.setGeometry(QtCore.QRect(240, 400, 200, 30))
        self.input_nombre.setObjectName("input_nombre")
        self.input_marca = QtWidgets.QLineEdit(self.centralwidget)
        self.input_marca.setGeometry(QtCore.QRect(460, 400, 200, 30))
        self.input_marca.setObjectName("input_marca")
        self.input_modelo = QtWidgets.QLineEdit(self.centralwidget)
        self.input_modelo.setGeometry(QtCore.QRect(680, 400, 200, 30))
        self.input_modelo.setObjectName("input_modelo")
        self.input_asientos_normal = QtWidgets.QLineEdit(self.centralwidget)
        self.input_asientos_normal.setGeometry(QtCore.QRect(20, 440, 200, 30))
        self.input_asientos_normal.setObjectName("input_asientos_normal")
        self.input_asientos_turista = QtWidgets.QLineEdit(self.centralwidget)
        self.input_asientos_turista.setGeometry(QtCore.QRect(240, 440, 200, 30))
        self.input_asientos_turista.setObjectName("input_asientos_turista")
        self.input_asientos_premium = QtWidgets.QLineEdit(self.centralwidget)
        self.input_asientos_premium.setGeometry(QtCore.QRect(460, 440, 200, 30))
        self.input_asientos_premium.setObjectName("input_asientos_premium")
        self.input_kilometraje = QtWidgets.QLineEdit(self.centralwidget)
        self.input_kilometraje.setGeometry(QtCore.QRect(680, 440, 200, 30))
        self.input_kilometraje.setObjectName("input_kilometraje")
        self.checkbox_en_vuelo = QtWidgets.QCheckBox(self.centralwidget)
        self.checkbox_en_vuelo.setGeometry(QtCore.QRect(20, 480, 200, 30))
        self.checkbox_en_vuelo.setObjectName("checkbox_en_vuelo")
        self.label_estadisticas = QtWidgets.QLabel(self.centralwidget)
        self.label_estadisticas.setGeometry(QtCore.QRect(20, 520, 850, 30))
        self.label_estadisticas.setObjectName("label_estadisticas")
        self.btn_volver_menu = QtWidgets.QPushButton(self.centralwidget)
        self.btn_volver_menu.setGeometry(QtCore.QRect(20, 560, 120, 30))
        self.btn_volver_menu.setObjectName("btn_volver_menu")
        AdminPanelWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(AdminPanelWindow)
        self.menubar.setObjectName("menubar")
        AdminPanelWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(AdminPanelWindow)
        self.statusbar.setObjectName("statusbar")
        AdminPanelWindow.setStatusBar(self.statusbar)

        self.retranslateUi(AdminPanelWindow)
        QtCore.QMetaObject.connectSlotsByName(AdminPanelWindow)

    def retranslateUi(self, AdminPanelWindow):
        _translate = QtCore.QCoreApplication.translate
        AdminPanelWindow.setWindowTitle(_translate("AdminPanelWindow", "Panel de Administración - Aerolínea XYZ"))
        self.btn_ver_aviones.setText(_translate("AdminPanelWindow", "Ver Aviones"))
        self.btn_agregar_avion.setText(_translate("AdminPanelWindow", "Agregar Avión"))
        self.btn_modificar_avion.setText(_translate("AdminPanelWindow", "Modificar Avión"))
        self.btn_eliminar_avion.setText(_translate("AdminPanelWindow", "Eliminar Avión"))
        self.input_matricula.setPlaceholderText(_translate("AdminPanelWindow", "Matrícula"))
        self.input_nombre.setPlaceholderText(_translate("AdminPanelWindow", "Nombre"))
        self.input_marca.setPlaceholderText(_translate("AdminPanelWindow", "Marca"))
        self.input_modelo.setPlaceholderText(_translate("AdminPanelWindow", "Modelo"))
        self.input_asientos_normal.setPlaceholderText(_translate("AdminPanelWindow", "Asientos Normal"))
        self.input_asientos_turista.setPlaceholderText(_translate("AdminPanelWindow", "Asientos Turista"))
        self.input_asientos_premium.setPlaceholderText(_translate("AdminPanelWindow", "Asientos Premium"))
        self.input_kilometraje.setPlaceholderText(_translate("AdminPanelWindow", "Kilometraje"))
        self.checkbox_en_vuelo.setText(_translate("AdminPanelWindow", "En Vuelo"))
        self.label_estadisticas.setText(_translate("AdminPanelWindow", "Estadísticas"))
        self.btn_volver_menu.setText(_translate("AdminPanelWindow", "Volver al Menú"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AdminPanelWindow = QtWidgets.QMainWindow()
    ui = Ui_AdminPanelWindow()
    ui.setupUi(AdminPanelWindow)
    AdminPanelWindow.show()
    sys.exit(app.exec_())
