# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginWindow(object):
    def setupUi(self, LoginWindow):
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.resize(600, 400)
        LoginWindow.setStyleSheet("background-color: rgb(30, 60, 90); color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(LoginWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.logo = QtWidgets.QLabel(self.centralwidget)
        self.logo.setGeometry(QtCore.QRect(250, 30, 100, 100))
        self.logo.setPixmap(QtGui.QPixmap("imagenes/logo.png"))
        self.logo.setAlignment(QtCore.Qt.AlignCenter)
        self.logo.setObjectName("logo")
        self.titulo = QtWidgets.QLabel(self.centralwidget)
        self.titulo.setGeometry(QtCore.QRect(150, 140, 300, 40))
        self.titulo.setAlignment(QtCore.Qt.AlignCenter)
        self.titulo.setStyleSheet("font: 20pt \"Segoe UI\"; color: rgb(255, 255, 255);")
        self.titulo.setObjectName("titulo")
        self.label_usuario = QtWidgets.QLabel(self.centralwidget)
        self.label_usuario.setGeometry(QtCore.QRect(150, 200, 80, 30))
        self.label_usuario.setStyleSheet("font: 12pt \"Segoe UI\";")
        self.label_usuario.setObjectName("label_usuario")
        self.input_usuario = QtWidgets.QLineEdit(self.centralwidget)
        self.input_usuario.setGeometry(QtCore.QRect(240, 200, 200, 30))
        self.input_usuario.setStyleSheet("background-color: rgb(255, 255, 255); color: rgb(0, 0, 0);")
        self.input_usuario.setObjectName("input_usuario")
        self.label_contrasena = QtWidgets.QLabel(self.centralwidget)
        self.label_contrasena.setGeometry(QtCore.QRect(150, 250, 80, 30))
        self.label_contrasena.setStyleSheet("font: 12pt \"Segoe UI\";")
        self.label_contrasena.setObjectName("label_contrasena")
        self.input_contrasena = QtWidgets.QLineEdit(self.centralwidget)
        self.input_contrasena.setGeometry(QtCore.QRect(240, 250, 200, 30))
        self.input_contrasena.setEchoMode(QtWidgets.QLineEdit.Password)
        self.input_contrasena.setStyleSheet("background-color: rgb(255, 255, 255); color: rgb(0, 0, 0);")
        self.input_contrasena.setObjectName("input_contrasena")
        self.boton_ingresar = QtWidgets.QPushButton(self.centralwidget)
        self.boton_ingresar.setGeometry(QtCore.QRect(240, 300, 200, 40))
        self.boton_ingresar.setStyleSheet("background-color: rgb(0, 123, 255); font: bold 14pt \"Segoe UI\"; color: rgb(255, 255, 255);")
        self.boton_ingresar.setObjectName("boton_ingresar")
        self.label_error = QtWidgets.QLabel(self.centralwidget)
        self.label_error.setGeometry(QtCore.QRect(150, 360, 300, 20))
        self.label_error.setAlignment(QtCore.Qt.AlignCenter)
        self.label_error.setStyleSheet("color: rgb(255, 0, 0); font: italic 10pt \"Segoe UI\";")
        self.label_error.setObjectName("label_error")
        LoginWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(LoginWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 30))
        self.menubar.setObjectName("menubar")
        LoginWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(LoginWindow)
        self.statusbar.setObjectName("statusbar")
        LoginWindow.setStatusBar(self.statusbar)

        self.retranslateUi(LoginWindow)
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "Aerolinea XYZ - Inicio de Sesión"))
        self.titulo.setText(_translate("LoginWindow", "Aerolinea XYZ - Inicio de Sesión"))
        self.label_usuario.setText(_translate("LoginWindow", "Usuario:"))
        self.input_usuario.setPlaceholderText(_translate("LoginWindow", "Ingrese su usuario"))
        self.label_contrasena.setText(_translate("LoginWindow", "Contraseña:"))
        self.input_contrasena.setPlaceholderText(_translate("LoginWindow", "Ingrese su contraseña"))
        self.boton_ingresar.setText(_translate("LoginWindow", "Ingresar"))
        self.label_error.setText(_translate("LoginWindow", "Mensaje de error aquí"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LoginWindow = QtWidgets.QMainWindow()
    ui = Ui_LoginWindow()
    ui.setupUi(LoginWindow)
    LoginWindow.show()
    sys.exit(app.exec_())
