# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menu_principal.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MenuPrincipalWindow(object):
    def setupUi(self, MenuPrincipalWindow):
        MenuPrincipalWindow.setObjectName("MenuPrincipalWindow")
        MenuPrincipalWindow.resize(400, 300)
        MenuPrincipalWindow.setStyleSheet("background-color: rgb(0, 102, 204);")
        self.centralwidget = QtWidgets.QWidget(MenuPrincipalWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_gestionar_reservas = QtWidgets.QPushButton(self.centralwidget)
        self.btn_gestionar_reservas.setGeometry(QtCore.QRect(100, 80, 200, 50))
        self.btn_gestionar_reservas.setStyleSheet("background-color: rgb(255, 255, 255); color: rgb(0, 0, 0); font-size: 16px; border-radius: 10px;")
        self.btn_gestionar_reservas.setObjectName("btn_gestionar_reservas")
        self.btn_gestionar_vuelos = QtWidgets.QPushButton(self.centralwidget)
        self.btn_gestionar_vuelos.setGeometry(QtCore.QRect(100, 150, 200, 50))
        self.btn_gestionar_vuelos.setStyleSheet("background-color: rgb(255, 255, 255); color: rgb(0, 0, 0); font-size: 16px; border-radius: 10px;")
        self.btn_gestionar_vuelos.setObjectName("btn_gestionar_vuelos")
        MenuPrincipalWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MenuPrincipalWindow)
        self.menubar.setObjectName("menubar")
        MenuPrincipalWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MenuPrincipalWindow)
        self.statusbar.setObjectName("statusbar")
        MenuPrincipalWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MenuPrincipalWindow)
        QtCore.QMetaObject.connectSlotsByName(MenuPrincipalWindow)

    def retranslateUi(self, MenuPrincipalWindow):
        _translate = QtCore.QCoreApplication.translate
        MenuPrincipalWindow.setWindowTitle(_translate("MenuPrincipalWindow", "Menú Principal - Aerolínea XYZ"))
        self.btn_gestionar_reservas.setText(_translate("MenuPrincipalWindow", "Gestionar Reservas"))
        self.btn_gestionar_vuelos.setText(_translate("MenuPrincipalWindow", "Gestionar Vuelos"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MenuPrincipalWindow = QtWidgets.QMainWindow()
    ui = Ui_MenuPrincipalWindow()
    ui.setupUi(MenuPrincipalWindow)
    MenuPrincipalWindow.show()
    sys.exit(app.exec_())
