# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'reservas_panel.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ReservasPanelWindow(object):
    def setupUi(self, ReservasPanelWindow):
        ReservasPanelWindow.setObjectName("ReservasPanelWindow")
        ReservasPanelWindow.resize(900, 600)
        self.centralwidget = QtWidgets.QWidget(ReservasPanelWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_ver_reservas = QtWidgets.QPushButton(self.centralwidget)
        self.btn_ver_reservas.setGeometry(QtCore.QRect(20, 20, 120, 30))
        self.btn_ver_reservas.setObjectName("btn_ver_reservas")
        self.btn_agregar_reserva = QtWidgets.QPushButton(self.centralwidget)
        self.btn_agregar_reserva.setGeometry(QtCore.QRect(160, 20, 120, 30))
        self.btn_agregar_reserva.setObjectName("btn_agregar_reserva")
        self.btn_modificar_reserva = QtWidgets.QPushButton(self.centralwidget)
        self.btn_modificar_reserva.setGeometry(QtCore.QRect(300, 20, 120, 30))
        self.btn_modificar_reserva.setObjectName("btn_modificar_reserva")
        self.btn_eliminar_reserva = QtWidgets.QPushButton(self.centralwidget)
        self.btn_eliminar_reserva.setGeometry(QtCore.QRect(440, 20, 120, 30))
        self.btn_eliminar_reserva.setObjectName("btn_eliminar_reserva")
        self.tabla_reservas = QtWidgets.QTableWidget(self.centralwidget)
        self.tabla_reservas.setGeometry(QtCore.QRect(20, 70, 850, 300))
        self.tabla_reservas.setColumnCount(7)
        self.tabla_reservas.setRowCount(0)
        self.tabla_reservas.setObjectName("tabla_reservas")
        self.input_dni_pasajero = QtWidgets.QLineEdit(self.centralwidget)
        self.input_dni_pasajero.setGeometry(QtCore.QRect(20, 390, 200, 30))
        self.input_dni_pasajero.setObjectName("input_dni_pasajero")
        self.input_nombre_pasajero = QtWidgets.QLineEdit(self.centralwidget)
        self.input_nombre_pasajero.setGeometry(QtCore.QRect(240, 390, 200, 30))
        self.input_nombre_pasajero.setObjectName("input_nombre_pasajero")
        self.input_apellido_pasajero = QtWidgets.QLineEdit(self.centralwidget)
        self.input_apellido_pasajero.setGeometry(QtCore.QRect(460, 390, 200, 30))
        self.input_apellido_pasajero.setObjectName("input_apellido_pasajero")
        self.input_vuelo_id = QtWidgets.QLineEdit(self.centralwidget)
        self.input_vuelo_id.setGeometry(QtCore.QRect(680, 390, 200, 30))
        self.input_vuelo_id.setObjectName("input_vuelo_id")
        self.input_fecha_creacion = QtWidgets.QDateEdit(self.centralwidget)
        self.input_fecha_creacion.setGeometry(QtCore.QRect(460, 430, 200, 30))
        self.input_fecha_creacion.setCalendarPopup(True)
        self.input_fecha_creacion.setObjectName("input_fecha_creacion")
        self.input_estado_reserva = QtWidgets.QComboBox(self.centralwidget)
        self.input_estado_reserva.setGeometry(QtCore.QRect(20, 430, 200, 30))
        self.input_estado_reserva.setObjectName("input_estado_reserva")
        self.input_estado_reserva.addItem("")
        self.input_estado_reserva.addItem("")
        self.input_asiento_clase = QtWidgets.QComboBox(self.centralwidget)
        self.input_asiento_clase.setGeometry(QtCore.QRect(240, 430, 200, 30))
        self.input_asiento_clase.setObjectName("input_asiento_clase")
        self.input_asiento_clase.addItem("")
        self.input_asiento_clase.addItem("")
        self.input_asiento_clase.addItem("")
        self.input_precio = QtWidgets.QLineEdit(self.centralwidget)
        self.input_precio.setGeometry(QtCore.QRect(680, 430, 200, 30))
        self.input_precio.setObjectName("input_precio")
        self.label_estadisticas = QtWidgets.QLabel(self.centralwidget)
        self.label_estadisticas.setGeometry(QtCore.QRect(20, 470, 850, 30))
        self.label_estadisticas.setObjectName("label_estadisticas")
        self.btn_volver_menu = QtWidgets.QPushButton(self.centralwidget)
        self.btn_volver_menu.setGeometry(QtCore.QRect(20, 520, 120, 30))
        self.btn_volver_menu.setObjectName("btn_volver_menu")
        ReservasPanelWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ReservasPanelWindow)
        self.menubar.setObjectName("menubar")
        ReservasPanelWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ReservasPanelWindow)
        self.statusbar.setObjectName("statusbar")
        ReservasPanelWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ReservasPanelWindow)
        QtCore.QMetaObject.connectSlotsByName(ReservasPanelWindow)

    def retranslateUi(self, ReservasPanelWindow):
        _translate = QtCore.QCoreApplication.translate
        ReservasPanelWindow.setWindowTitle(_translate("ReservasPanelWindow", "Panel de Reservas - Aerolínea XYZ"))
        self.btn_ver_reservas.setText(_translate("ReservasPanelWindow", "Ver Reservas"))
        self.btn_agregar_reserva.setText(_translate("ReservasPanelWindow", "Agregar Reserva"))
        self.btn_modificar_reserva.setText(_translate("ReservasPanelWindow", "Modificar Reserva"))
        self.btn_eliminar_reserva.setText(_translate("ReservasPanelWindow", "Eliminar Reserva"))
        self.input_dni_pasajero.setPlaceholderText(_translate("ReservasPanelWindow", "DNI del Pasajero"))
        self.input_nombre_pasajero.setPlaceholderText(_translate("ReservasPanelWindow", "Nombre del Pasajero"))
        self.input_apellido_pasajero.setPlaceholderText(_translate("ReservasPanelWindow", "Apellido del Pasajero"))
        self.input_vuelo_id.setPlaceholderText(_translate("ReservasPanelWindow", "ID Vuelo"))
        self.input_estado_reserva.setItemText(0, _translate("ReservasPanelWindow", "Pagada"))
        self.input_estado_reserva.setItemText(1, _translate("ReservasPanelWindow", "En Espera"))
        self.input_asiento_clase.setItemText(0, _translate("ReservasPanelWindow", "Normal"))
        self.input_asiento_clase.setItemText(1, _translate("ReservasPanelWindow", "Turista"))
        self.input_asiento_clase.setItemText(2, _translate("ReservasPanelWindow", "Premium"))
        self.input_precio.setPlaceholderText(_translate("ReservasPanelWindow", "Precio"))
        self.label_estadisticas.setText(_translate("ReservasPanelWindow", "Estadísticas"))
        self.btn_volver_menu.setText(_translate("ReservasPanelWindow", "Volver al Menú"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ReservasPanelWindow = QtWidgets.QMainWindow()
    ui = Ui_ReservasPanelWindow()
    ui.setupUi(ReservasPanelWindow)
    ReservasPanelWindow.show()
    sys.exit(app.exec_())
