# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vuelos_panel.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VuelosPanelWindow(object):
    def setupUi(self, VuelosPanelWindow):
        VuelosPanelWindow.setObjectName("VuelosPanelWindow")
        VuelosPanelWindow.resize(900, 600)
        self.centralwidget = QtWidgets.QWidget(VuelosPanelWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_ver_vuelos = QtWidgets.QPushButton(self.centralwidget)
        self.btn_ver_vuelos.setGeometry(QtCore.QRect(20, 20, 100, 30))
        self.btn_ver_vuelos.setObjectName("btn_ver_vuelos")
        self.btn_agregar_vuelo = QtWidgets.QPushButton(self.centralwidget)
        self.btn_agregar_vuelo.setGeometry(QtCore.QRect(130, 20, 100, 30))
        self.btn_agregar_vuelo.setObjectName("btn_agregar_vuelo")
        self.btn_modificar_vuelo = QtWidgets.QPushButton(self.centralwidget)
        self.btn_modificar_vuelo.setGeometry(QtCore.QRect(240, 20, 100, 30))
        self.btn_modificar_vuelo.setObjectName("btn_modificar_vuelo")
        self.btn_eliminar_vuelo = QtWidgets.QPushButton(self.centralwidget)
        self.btn_eliminar_vuelo.setGeometry(QtCore.QRect(350, 20, 100, 30))
        self.btn_eliminar_vuelo.setObjectName("btn_eliminar_vuelo")
        self.tabla_vuelos = QtWidgets.QTableWidget(self.centralwidget)
        self.tabla_vuelos.setGeometry(QtCore.QRect(20, 70, 850, 300))
        self.tabla_vuelos.setColumnCount(6)
        self.tabla_vuelos.setRowCount(0)
        self.tabla_vuelos.setObjectName("tabla_vuelos")
        self.input_avion_id = QtWidgets.QLineEdit(self.centralwidget)
        self.input_avion_id.setGeometry(QtCore.QRect(20, 390, 200, 30))
        self.input_avion_id.setObjectName("input_avion_id")
        self.input_origen = QtWidgets.QLineEdit(self.centralwidget)
        self.input_origen.setGeometry(QtCore.QRect(240, 390, 200, 30))
        self.input_origen.setObjectName("input_origen")
        self.input_destino = QtWidgets.QLineEdit(self.centralwidget)
        self.input_destino.setGeometry(QtCore.QRect(460, 390, 200, 30))
        self.input_destino.setObjectName("input_destino")
        self.input_fecha_partida = QtWidgets.QDateEdit(self.centralwidget)
        self.input_fecha_partida.setGeometry(QtCore.QRect(680, 390, 200, 30))
        self.input_fecha_partida.setCalendarPopup(True)
        self.input_fecha_partida.setObjectName("input_fecha_partida")
        self.input_fecha_llegada = QtWidgets.QDateEdit(self.centralwidget)
        self.input_fecha_llegada.setGeometry(QtCore.QRect(680, 430, 200, 30))
        self.input_fecha_llegada.setCalendarPopup(True)
        self.input_fecha_llegada.setObjectName("input_fecha_llegada")
        self.label_estadisticas = QtWidgets.QLabel(self.centralwidget)
        self.label_estadisticas.setGeometry(QtCore.QRect(20, 470, 850, 30))
        self.label_estadisticas.setObjectName("label_estadisticas")
        self.btn_volver_menu = QtWidgets.QPushButton(self.centralwidget)
        self.btn_volver_menu.setGeometry(QtCore.QRect(20, 520, 120, 30))
        self.btn_volver_menu.setObjectName("btn_volver_menu")
        VuelosPanelWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(VuelosPanelWindow)
        self.menubar.setObjectName("menubar")
        VuelosPanelWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(VuelosPanelWindow)
        self.statusbar.setObjectName("statusbar")
        VuelosPanelWindow.setStatusBar(self.statusbar)

        self.retranslateUi(VuelosPanelWindow)
        QtCore.QMetaObject.connectSlotsByName(VuelosPanelWindow)

    def retranslateUi(self, VuelosPanelWindow):
        _translate = QtCore.QCoreApplication.translate
        VuelosPanelWindow.setWindowTitle(_translate("VuelosPanelWindow", "Panel de Vuelos - Aerolínea XYZ"))
        self.btn_ver_vuelos.setText(_translate("VuelosPanelWindow", "Ver Vuelos"))
        self.btn_agregar_vuelo.setText(_translate("VuelosPanelWindow", "Agregar Vuelo"))
        self.btn_modificar_vuelo.setText(_translate("VuelosPanelWindow", "Modificar Vuelo"))
        self.btn_eliminar_vuelo.setText(_translate("VuelosPanelWindow", "Eliminar Vuelo"))
        self.input_avion_id.setPlaceholderText(_translate("VuelosPanelWindow", "ID Avión"))
        self.input_origen.setPlaceholderText(_translate("VuelosPanelWindow", "Ciudad Origen"))
        self.input_destino.setPlaceholderText(_translate("VuelosPanelWindow", "Ciudad Destino"))
        self.input_fecha_partida.setPlaceholderText(_translate("VuelosPanelWindow", "Fecha de Partida"))
        self.input_fecha_llegada.setPlaceholderText(_translate("VuelosPanelWindow", "Fecha de Llegada"))
        self.label_estadisticas.setText(_translate("VuelosPanelWindow", "Estadísticas"))
        self.btn_volver_menu.setText(_translate("VuelosPanelWindow", "Volver al Menú"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    VuelosPanelWindow = QtWidgets.QMainWindow()
    ui = Ui_VuelosPanelWindow()
    ui.setupUi(VuelosPanelWindow)
    VuelosPanelWindow.show()
    sys.exit(app.exec_())
